FROM nginx:alpine

# Copy React build
COPY build/ /usr/share/nginx/html

# Copy NGINX config from inside frontend folder
COPY nginx/app.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]